import React, { useCallback, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useCheckInStorage } from './useStorage';
import { Deck, Question } from '../shared/types';
import NetInfo, { NetInfoState } from '@react-native-community/netinfo';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Session } from '@supabase/supabase-js';
import { AppState, AppStateStatus } from 'react-native';

interface SupabaseContextType {
  session: Session | null;
  loadingSession: boolean;
  pairWithDoctor: (pairingCode: string) => Promise<boolean>;
  activeDeck: { deck: Deck; questions: Question[] } | null;
  loadingDeck: boolean;
  submitResponse: (questionId: string, value: any, skipped: boolean, sessionId: string) => Promise<void>;
  createCheckInSession: (totalQuestions: number) => Promise<string>;
  simulateHistory: (days?: number) => Promise<boolean>;
  refreshDeck: () => Promise<void>;
  syncing: boolean;
  patientProfile: any;
}

const SupabaseContext = React.createContext<SupabaseContextType | null>(null);

export function SupabaseProvider({ children }: { children: React.ReactNode }) {
  const [session, setSession] = useState<Session | null>(null);
  const [loadingSession, setLoadingSession] = useState(true);
  const [activeDeck, setActiveDeck] = useState<{ deck: Deck; questions: Question[] } | null>(null);
  const [patientProfile, setPatientProfile] = useState<any>(null);
  const [loadingDeck, setLoadingDeck] = useState(false);
  const [syncing, setSyncing] = useState(false);

  // ── HOISTED CALLBACKS ── 
  const fetchActiveDeck = useCallback(async () => {
    if (!session) return;
    
    setLoadingDeck(true);
    try {
      // 1. Fetch Patient Profile & Doctor Name via implicit FK join
      const { data: profile } = await supabase
        .from('patients')
        .select('*, doctors(name)')
        .eq('id', session.user.id)
        .single();
      if (profile) setPatientProfile(profile);

      // 2. Fetch active deck for this patient
      const { data: decks, error: deckError } = await supabase
        .from('decks')
        .select('*')
        .eq('status', 'active')
        .order('created_at', { ascending: false })
        .limit(1);

      if (deckError || !decks || decks.length === 0) {
        setActiveDeck(null);
        return;
      }

      const deck = decks[0] as Deck;

      // Fetch questions for this deck
      const { data: questions, error: qError } = await supabase
        .from('questions')
        .select('*')
        .eq('deck_id', deck.id)
        .order('order', { ascending: true });

      if (qError) throw qError;

      setActiveDeck({ deck, questions: questions as Question[] });
    } catch (e) {
      console.error('💥 [Sync] Error fetching deck:', e);
      setActiveDeck(null); // Fallback to offline/empty
    } finally {
      setLoadingDeck(false);
    }
  }, [session]);

  const pairWithDoctor = async (pairingCode: string) => {
    const code = pairingCode.toUpperCase().trim();
    // We use a deterministic email/password generated by the doctor dashboard to sign in securely
    const { data, error } = await supabase.auth.signInWithPassword({
      email: `${code}@penguinpals.health`,
      password: `${code}-securepass123`,
    });

    if (error) {
      console.error('Pairing failed:', error.message);
      throw new Error('Invalid pairing code. Please check with your doctor.');
    }
    
    // Check if the pairing code is expired
    const { data: patient } = await supabase
      .from('patients')
      .select('*')
      .eq('id', data.user.id)
      .single();

    if (patient && new Date(patient.pairing_code_expires_at) < new Date()) {
      await supabase.auth.signOut();
      throw new Error('This pairing code has expired.');
    }

    return true;
  };

  // Auth state listener
  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session as any);
      if (session) fetchActiveDeck();
      setLoadingSession(false);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session as any);
      if (session) fetchActiveDeck();
      else setActiveDeck(null);
      setLoadingSession(false);
    });

    return () => subscription.unsubscribe();
  }, []);

  // Foreground Data Sync
  useEffect(() => {
    const subscription = AppState.addEventListener('change', (nextAppState: AppStateStatus) => {
      // Refresh network requests cleanly when the user foregrounds the Mobile App
      if (nextAppState === 'active' && session) {
        fetchActiveDeck();
        syncPendingResponses();
      }
    });

    return () => {
      subscription.remove();
    };
  }, [session, fetchActiveDeck]);

  // Live Auto-Polling (simulates Reatime push without Postgres Websockets)
  useEffect(() => {
    if (!session) return;
    const interval = setInterval(() => {
      fetchActiveDeck();
    }, 10000); // Poll every 10s exclusively while app is mounted

    return () => clearInterval(interval);
  }, [session, fetchActiveDeck]);

  // Offline Sync Listener
  useEffect(() => {
    const unsubscribe = NetInfo.addEventListener((state: NetInfoState) => {
      if (state.isConnected && session) {
        syncPendingResponses();
      }
    });
    return unsubscribe;
  }, [session]);


  // Queue response for offline-first sync
  const submitResponse = async (questionId: string, value: any, skipped: boolean, sessionId: string) => {
    if (!activeDeck || !session) return;

    const payload = {
      question_id: questionId,
      patient_id: session.user.id,
      deck_id: activeDeck.deck.id,
      session_id: sessionId,
      value,
      skipped,
      answered_at: new Date().toISOString()
    };

    // Always cache locally first
    const Q_KEY = '@penguinpals:pending_responses';
    const pending = JSON.parse((await AsyncStorage.getItem(Q_KEY)) || '[]');
    pending.push(payload);
    await AsyncStorage.setItem(Q_KEY, JSON.stringify(pending));

    // Try background sync immediately
    syncPendingResponses();
  };

  // Sync queued responses to Supabase
  const syncPendingResponses = async () => {
    if (syncing) return;
    setSyncing(true);

    const Q_KEY = '@penguinpals:pending_responses';
    try {
      const pending: any[] = JSON.parse((await AsyncStorage.getItem(Q_KEY)) || '[]');
      if (pending.length === 0) return;

      const { error } = await supabase.from('responses').insert(pending);
      
      if (!error) {
        // Success - clear queue
        await AsyncStorage.removeItem(Q_KEY);
      } else {
        console.error('Sync error:', error.message);
      }
    } catch (e) {
      console.error('Offline sync failed', e);
    } finally {
      setSyncing(false);
    }
  };

  const createCheckInSession = async (totalQuestions: number) => {
    if (!activeDeck || !session) return 'offline-session-id';
    
    // In a real robust offline system, we'd also queue session creation.
    // For simplicity, if online we create it.
    const { data } = await supabase.from('check_in_sessions').insert([{
      patient_id: session.user.id,
      deck_id: activeDeck.deck.id,
      questions_total: totalQuestions,
      questions_answered: 0
    }]).select('id').single();

    return data?.id || 'offline-session-id';
  };

  const simulateHistory = async (days: number = 30) => {
    if (!activeDeck || !session) throw new Error('Not paired or no active deck');
    
    setSyncing(true);
    try {
      const patientId = session.user.id;
      const deckId = activeDeck.deck.id;
      const totalQuestions = activeDeck.questions.length;
      
      const sessionInserts: any[] = [];
      const now = new Date();
      
      for (let i = days; i >= 1; i--) {
        const pastDate = new Date(now);
        pastDate.setDate(now.getDate() - i);
        // Add random time jitter within check-in window (9pm - 10pm)
        pastDate.setHours(21, Math.floor(Math.random() * 60));
        
        const timestamp = pastDate.toISOString();
        
        sessionInserts.push({
          patient_id: patientId,
          deck_id: deckId,
          questions_total: totalQuestions,
          questions_answered: totalQuestions,
          completed_at: timestamp
        });
      }
      
      // Bulk insert sessions and return IDs to link responses
      const { data: insertedSessions, error: sessionErr } = await supabase
        .from('check_in_sessions')
        .insert(sessionInserts)
        .select('id, completed_at');
        
      if (sessionErr || !insertedSessions) throw sessionErr || new Error('Failed to insert sessions');
      
      const responseInserts: any[] = [];
      
      insertedSessions.forEach(sess => {
        const timestamp = sess.completed_at;
        // Basic temporal drift: slight chance of feeling worse randomly to create jitter in the chart
        const isBadDay = Math.random() < 0.15; 
        
        activeDeck.questions.forEach(q => {
           let val: any = null;
           
           if (q.type === 'scale_10') val = isBadDay ? Math.floor(Math.random() * 4) + 2 : Math.floor(Math.random() * 3) + 7;
           else if (q.type === 'scale_7') val = isBadDay ? Math.floor(Math.random() * 2) + 2 : Math.floor(Math.random() * 2) + 5;
           else if (q.type === 'scale_5') val = isBadDay ? Math.floor(Math.random() * 2) + 1 : Math.floor(Math.random() * 2) + 4;
           else if (q.type === 'yes_no') val = !isBadDay;
           else if (q.type === 'multi_choice') val = q.config.options?.[0];
           else if (q.type === 'multi_select') val = [q.config.options?.[0]];
           else val = "Simulated answer";
           
           responseInserts.push({
             question_id: q.id,
             patient_id: patientId,
             deck_id: deckId,
             session_id: sess.id,
             value: val,
             skipped: false,
             answered_at: timestamp
           });
        });
      });
      
      // Bulk insert responses
      const { error: responseErr } = await supabase
        .from('responses')
        .insert(responseInserts);
        
      if (responseErr) throw responseErr;
      
      // Update patient streak completely
      await supabase.from('patients').update({ streak: days }).eq('id', patientId);
      
      return true;
    } catch(e) {
      console.error('Simulation Failed:', e);
      throw e;
    } finally {
      setSyncing(false);
    }
  };

  return (
    <SupabaseContext.Provider
      value={{
        session,
        loadingSession,
        pairWithDoctor,
        activeDeck,
        loadingDeck,
        submitResponse,
        createCheckInSession,
        simulateHistory,
        refreshDeck: fetchActiveDeck,
        syncing,
        patientProfile,
      }}
    >
      {children}
    </SupabaseContext.Provider>
  );
}

export function useSupabase() {
  const context = React.useContext(SupabaseContext);
  if (!context) {
    throw new Error('useSupabase must be used within a SupabaseProvider');
  }
  return context;
}
